name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-package
          path: ./dist

  gh-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: release-package
          path: ./release-content

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-content/**

  publish-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-package
          path: ./release-content

      - name: Extract Archive
        run: tar -xzvf release-content/release-package.tar.gz -C ./release-content

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com

      - name: Publish to GitHub Packages
        run: npm publish ./release-content
